Promise.resolve()
.then(() => console.log(1))
.then(() => console.log(2))
.then(() => {
  console.log(3)
  return Promise.resolve(4)
})
.then(res => console.log(res))

Promise.resolve()
.then(() => console.log(5))
.then(() => console.log(6))
.then(() => console.log(7))
.then(() => console.log(8))
.then(() => console.log(9))
.then(() => console.log(10))